version: "3"
services:
    mysqldb:
        image: mysql
        restart: always
        env_file: ./.env
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
        ports:
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        volumes: 
            - db-config:/etc/mysql
            - db-data:/var/lib/mysql:rw
            - ./db/backup/files/:/data_backup/data
    backend:
        container_name: aspire_backend
        build:
            context: .
            dockerfile: Dockerfile
        image: aspire_backend:latest
        ports:
            - "5000:3000"
        volumes:
            - ./:/usr/src/app
            - server_node_modules:/usr/src/app/node_modules
        depends_on:
            - mysqldb
        environment:
            - MYSQL_HOST=$MYSQL_HOST
            - MYSQL_USERNAME=$MYSQL_USERNAME
            - MYSQL_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_PORT=$MYSQL_DOCKER_PORT
    phpmyadmin:
        container_name: aspire_phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: mysqldb
            PMA_USER: $MYSQL_USERNAME
            PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
        depends_on:
            - mysqldb
        ports:
            - "8081:80"
volumes: 
  db-config:
  db-data:
  node_modules:
  server_node_modules: